version: '3.8'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile.nestjs
    container_name: nestjs-portfolio
    environment:
      - PORT=${PORT:-3000}
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge
