version: '3.8'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile.nestjs
    container_name: nestjs-portfolio
    environment:
      - PORT=${PORT:-3000}
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
    networks:
      - portfolio-network

  caddy:
    image: caddy:2.6.0
    container_name: caddy-http3
    ports:
      - "8080:8080"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge
